# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'CLAMap2DExmaple' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

	pod 'AMap2DMap'
    pod 'CLUIKit'
end
